Repository 67P/hubot-kredits, pull requests merged in 2019-08, with the labels that each got.

#42 Change threshold for small wiki contributions
  integrations/mediawiki.js
Labels: kredits-1

#43 Add ENV var for custom DAO address
  index.js
Labels: kredits-1

#41 Add GitHub signup oracle
  README.md
  integrations/github.js
  package-lock.json
  package.json
Labels: kredits-3

#45 Add GitHub signup oracle documentation
  README.md
  integrations/github.js
Labels: docs, kredits-2
