Repository 67P/hubot-kredits, pull requests merged in 2019-04, with the labels that each got.

#25 Update kredits contracts
  index.js
  integrations/github.js
  integrations/mediawiki.js
  package-lock.json
  package.json
Labels: in progress, kredits-2

#27 Create contributions instead of proposals
  README.md
  index.js
  integrations/github.js
  integrations/mediawiki.js
Labels: kredits-2

#32 Remove network ID setting
  README.md
  index.js
Labels: kredits-1

#31 Add Gitea integration
  README.md
  index.js
  integrations/gitea.js
  package-lock.json
  package.json
Labels: kredits-2

#35 Fix wrong Gitea issue IDs/URLs
  index.js
  integrations/gitea.js
Labels: kredits-1
